const js = require('@eslint/js');
const importPlugin = require('eslint-plugin-import');

module.exports = [
  {
    ignores: [
      'lib/**',
      'assets/**',
      'dist/**',
      '**/*.min.js',
      '**/*.min.css',
      '**/tesseract/**',
      'node_modules/**',
    ],
  },
  {
    files: ['eslint.config.js'],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'commonjs',
      globals: {
        module: 'readonly',
        require: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        process: 'readonly',
      },
    },
  },
  js.configs.recommended,
  {
    plugins: { import: importPlugin },
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'script',
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        caches: 'readonly',
        self: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        FileReader: 'readonly',
        Blob: 'readonly',
        AbortController: 'readonly',
        TextEncoder: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        ResizeObserver: 'readonly',
        Node: 'readonly',
        Event: 'readonly',
        screen: 'readonly',
        performance: 'readonly',
        history: 'readonly',
        location: 'readonly',
        idb: 'readonly',
        Fuse: 'readonly',
        Sortable: 'readonly',
        mammoth: 'readonly',
        Tesseract: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-undef': 'error',
      'no-console': 'off',
      'import/no-unresolved': 'off',
      'import/no-absolute-path': 'off',
    },
  },
];
